#!/bin/bash

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_8/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=8

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_10/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=10

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_15/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=15

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_20/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=20

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_30/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=30

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_40/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=40

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_50/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=50

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_60/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=60

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_70/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=70

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_80/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=80

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_90/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=90

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_100/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=100

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_110/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=110

python ../main/main.py \
        --data-root='../data/pacs/kfold/' \
        --save-root='../data/result_eps_120/dg_mmld/' \
        --result-dir='PACS/default/sketch1' \
        --train='general' \
        --data='PACS' \
        --model='caffenet' \
        --clustering \
        --clustering-method='Kmeans' \
        --num-clustering=3 \
        --clustering-step=1 \
        --entropy='default' \
        --exp-num=3 \
        --gpu=1 \
        --num-epoch=60 \
        --scheduler='step' \
        --lr=1e-3 \
        --lr-step=24 \
        --lr-decay-gamma=0.1 \
        --nesterov \
        --fc-weight=10.0 \
        --disc-weight=10.0 \
        --entropy-weight=1.0 \
        --grl-weight=1.0 \
        --loss-disc-weight \
        --color-jitter \
        --min-scale=0.8 \
        --instance-stat \
        --vat-eps=120